
name: Android Build and Deployment Pipeline

on:
  push:
    branches:
      - 'release_*'
      - 'new'

#   workflow_dispatch:
#     inputs:
#       app_id:
#         description: 'The application Id of the current build'
#         required: true
#       branch:
#         description: 'The branch from which we have to build'
#         required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew build

      - name: Generate app bundle
        run: ./gradlew app:bundleRelease --stacktrace
        
      - name: Sign app bundle
        run: |
          jarsigner -keystore app/*.jks \
          -storepass ${{ secrets.KEY_STORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} \
          app/build/outputs/bundle/release/app-release.aab ${{ secrets.ALIAS }}
          
#   STEP 2 : Upload the Artifact
  upload:
    needs: [ build ]
    name: Upload the signed artifact
    runs-on: ubuntu-latest
    steps:
      - name: Upload Bundle
        uses: actions/upload-artifact@v2
        with:
          name: signed_app_bundle
          path: app/build/outputs/bundle/release/app-release.aab
          
  
#   # Step 3 : Release to playstore
#   deploy:
#     needs: [ build ]
#     name: Create release on Playstore
#     runs-on: self-hosted
#     steps:
#       - name: Create service_account.json
#         run: echo '${{ secrets.SERVICE_ACCOUNT_JSON }}' > service_account.json

#       - name: Deploy to Play Store
#         uses: r0adkll/upload-google-play@v1.0.15
#         with:
#           serviceAccountJson: service_account.json
#           packageName: ${{ github.event.inputs.app_id }}
#           releaseFiles: app/build/outputs/bundle/release/*.aab
#           track: internal
#           whatsNewDirectory: whatsnew/
#           mappingFile: app/build/outputs/mapping/release/mapping.txt
#           inAppUpdatePriority: 5
